In [3]:
import pandas as pd
import pickle
import re
import numpy as np
import torch
from sklearn.model_selection import train_test_split

In [4]:
import tensorflow as tf
from tensorflow import keras

In [5]:
INP_PATH = '/data/sherin/'

In [107]:
df = pd.read_csv(INP_PATH + "memory_retention_raw.csv",
                         usecols=['index', 'seq_len', 'seq',
                                  'rep_token_first_pos',
                                  'query_token', 'target_val'])

In [102]:
df.iloc[35]

index                   35
seq_len                  1
seq                    [4]
rep_token_first_pos     -1
query_token             10
target_val               0
Name: 35, dtype: object

In [105]:
for s in ip_sequence:
    c = s[:-1]

(193714,)

In [104]:
df['actual_seq'] = 

array([array([19, 19]), array([72, 11]), array([87, 87]), ...,
       array([ 0, 30, 97, 44, 66, 69, 83, 21, 31, 34, 87, 28, 77, 22, 98, 86, 25,
              20,  3, 12, 50,  6, 71, 24, 91, 36, 43, 26, 90, 59, 72, 27, 64, 65,
               1, 14,  2, 40, 85, 92, 18,  9, 13, 88, 78, 93, 73, 51, 79, 58, 42,
              33, 60, 16, 47, 52, 74, 19, 82,  7, 37, 35, 10,  5, 41, 67, 84, 29,
              80, 45, 23,  4, 99, 94, 38, 89,  8, 49, 63, 76, 39, 70, 17, 54, 95,
              32, 81, 11, 61, 46, 57, 55, 56, 75, 53, 62, 68, 96, 15, 48])       ,
       array([ 4, 13, 64, 53, 77, 27, 39, 32, 16,  3, 35, 61, 62, 74, 73, 45, 82,
              10, 81, 34, 26, 56, 92, 58, 17, 75, 97,  9,  8, 52, 80, 30, 69, 89,
               0, 46, 11, 49, 70, 23, 86, 78, 95, 24,  7, 67, 91, 28, 33, 43, 20,
              60, 72,  1, 29, 57, 76, 14, 84, 99,  5, 12, 31, 38,  6, 48, 51,  2,
              21, 85, 83, 55, 98, 54, 88, 65, 66, 41, 15, 22, 44, 79, 63, 68, 94,
              87, 36, 37, 47, 59, 

In [8]:
df.head()

index  seq_len   seq  rep_token_first_pos  query_token  target_val
0      0        1  [19]                    0           19           1
1      1        1  [72]                   -1           11           0
2      2        1  [87]                    0           87           1
3      3        1   [8]                   -1           35           0
4      4        1  [74]                    0           74           1

In [108]:
df_train_val, df_test, ip_sequence_train_val, ip_sequence_test = train_test_split(
    df, ip_sequence,
    random_state=2,
    test_size=0.3)

In [111]:
df_train, df_val, ip_sequence_train, ip_sequence_val = train_test_split(
    df_train_val, ip_sequence_train_val,
    random_state=2,
    test_size=0.3)

In [116]:
df_test.iloc[59]

index                                                             185911
seq_len                                                               96
seq                    [47 98 11 82 55 89 46 27 28 24  4 71  2 95 81 ...
rep_token_first_pos                                                   -1
query_token                                                           59
target_val                                                             0
Name: 185911, dtype: object

In [117]:
ip_sequence_test[59]

array([47, 98, 11, 82, 55, 89, 46, 27, 28, 24,  4, 71,  2, 95, 81, 45, 73,
       26, 68, 66, 64, 51, 65, 34, 44, 93, 43, 54, 38, 70, 79, 92,  9, 86,
       20, 96,  5, 30, 42, 52, 41, 25,  3, 94,  7, 13, 97, 74, 48, 77, 56,
       40, 33, 31, 61, 15, 88, 90, 91, 53, 57, 67, 72, 23, 18, 69, 85, 12,
       14, 21, 83, 10, 17, 84, 19, 63, 37, 49, 78, 76, 99, 50, 36, 22, 29,
       58, 80,  6, 16, 87, 62, 32, 39,  1, 75, 60, 59])

In [121]:
# save df_test and ip_sequence_test for later analysis
np.save('test_context_query.npy', ip_sequence_test)

In [123]:
np.save('train_context_query.npy', ip_sequence_train)
np.save('val_context_query.npy', ip_sequence_val)

In [124]:
df_train.to_json('synthetic_train.json')
df_val.to_json('synthetic_val.json')
df_test.to_json('synthetic_test.json')

In [41]:
sequence_len = df['seq_len'].to_numpy()

In [11]:
raw_sequence = df['seq'].to_numpy()

In [13]:
rep_token_first_pos = df['rep_token_first_pos'].to_numpy()

In [43]:
token_repeated = df['query_token'].to_numpy()

In [61]:
token_repeated[1]

11

In [18]:
target_y = df['target_val'].to_numpy()

In [20]:
f = open(INP_PATH + 'input_data.pkl', 'rb')
x = pickle.load(f)
f.close()

In [21]:
orth_vectors = np.load(
    INP_PATH + 'orthonormal_vectors_512.npy')

In [22]:
f.close()

In [23]:
ip_sequence = np.load(INP_PATH + 'raw_sequence.npy',
                allow_pickle=True)

In [32]:
num_samples = len(x)

In [33]:
raw_sample_length = len(raw_sequence)

In [53]:
def process_data(max_seq_len, latent_dim, padding, memory_model, num_samples, x,
                 raw_sequence):
    # separate out the input to the encoder and the mlp
    # mlp is fed the last one hot encoded input
    x_mlp = [0] * num_samples
    x_encoder = [0] * num_samples

    for iter, seq in enumerate(x):
        # seq[-1] - eos seq[-2] - query token seq[0:-2] - seq
        x_mlp[iter] = seq[-2]
        # all but the last one hot encoded sequence
        x_encoder[iter] = seq[0:-2]
        # eos
        x_encoder[iter].append(seq[-1])

    # seq len + 1 for alphabet + eos as orthonormal vectors are created with eos
    # max size of seq len is not max seq len - 1 for the actual sequence + 1 for eos
    encoder_input_data = np.zeros((num_samples, max_seq_len,
                                   latent_dim * 2), dtype="float32")

    mlp_input_data = np.zeros((num_samples, latent_dim * 2), dtype="float32")

    if padding == 'pre_padding':
        print("The shape of the encoder data is: " + str(
            encoder_input_data.shape))
        for i in range(num_samples):
            seq_len = len(x_encoder[i])

            for seq in range(seq_len):
                # fill the elements in encoder_input_data in the reverse order,
                # this ensures that zero padding is done before the sequence
                encoder_input_data[i, max_seq_len - seq_len + seq] = \
                    x_encoder[i][seq]
            mlp_input_data[i] = x_mlp[i]
    elif padding == 'post_padding':

        for i in range(num_samples):
            seq_len = len(x_encoder[i])
            for seq in range(seq_len):
                encoder_input_data[i, seq] = x_encoder[i][seq]
            mlp_input_data[i] = x_mlp[i]

    if memory_model == "transformer_no_orthonormal":
        # remove the query token - the last token in raw_sequence
        sequence_raw = []
        for seq in raw_sequence:
            sequence_raw.append(seq[:-1])
        raw_sequence_padded = keras.preprocessing.sequence.pad_sequences(
            sequence_raw, maxlen=max_seq_len - 1, value=0)
    else:
        raw_sequence_padded = raw_sequence

    return encoder_input_data, mlp_input_data, raw_sequence_padded

In [54]:
max_seq_len = 100
latent_dim=256
nn_model = "lstm"

In [59]:
raw_sequence[1]

'[72]'

In [79]:
encoder_input_data, query_data, raw_sequence_padded = \
    process_data(max_seq_len, latent_dim, "pre_padding",
                     nn_model, num_samples,
                     x, raw_sequence)

The shape of the encoder data is: (193714, 100, 512)


In [81]:
# train test split
(encoder_input_data_train, encoder_input_data_test,
 query_train, query_test,
 target_y_train, target_y_test,
 sequence_len_train, sequence_len_test,
 token_repeated_train, token_repeated_test,
 rep_token_first_pos_train, rep_token_first_pos_test,
 raw_sequence_train, raw_sequence_test) = train_test_split(
    encoder_input_data,
    query_data,
    target_y,
    sequence_len,
    token_repeated,
    rep_token_first_pos,
    raw_sequence_padded,
    random_state=2,
    test_size=0.3)

In [82]:
# train val split
(encoder_input_train, encoder_input_val,
 query_input_train, query_input_val,
 target_train, target_val,
 sequence_length_train, sequence_length_val,
 token_rep_train, token_rep_val,
 rep_token_pos_train, rep_token_pos_val,
 raw_seq_train, raw_seq_val) = train_test_split(
    encoder_input_data_train,
    query_train,
    target_y_train,
    sequence_len_train,
    token_repeated_train,
    rep_token_first_pos_train,
    raw_sequence_train,
    random_state=2,
    test_size=0.3)

In [1]:
checkpoint_filepath_cnn = '/data/sherin/checkpoint_synthetic/best_model_CNN'
checkpoint_filepath_lstm = '/data/sherin/checkpoint_synthetic/best_model_lstm'

In [6]:
# load pre-trained model
model = keras.models.load_model(checkpoint_filepath_cnn)

2022-06-23 18:19:57.473850: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-06-23 18:19:57.474013: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-06-23 18:19:57.474105: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-06-23 18:19:57.474186: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libc

In [8]:
model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, None, 512)]  0           []                               
                                                                                                  
 conv1d (Conv1D)                (None, None, 128)    196736      ['input_3[0][0]']                
                                                                                                  
 conv1d_1 (Conv1D)              (None, None, 256)    98560       ['conv1d[0][0]']                 
                                                                                                  
 conv1d_2 (Conv1D)              (None, None, 512)    393728      ['conv1d_1[0][0]']               
                                                                                       

In [133]:
def sigmoid(x):
    z = np.exp(-1.0 * x)
    sig = 1.0 / (1.0 + z)
    return sig

In [134]:
def predict_model(model, target_val, encoder_input_val,
                  query_input_val):

    y_test = model.predict([encoder_input_val, query_input_val])
    y_test = sigmoid(y_test)
    # y_pred = np.argmax(y_test, axis=1)
    # for the kernel functions you would need values which are not 0 or 1
    y_pred_binary = np.array([1 if y > 0.5 else 0 for y in y_test])
    y_pred_continuous = y_test
    return y_pred_binary, y_pred_continuous

In [135]:
y_pred_binary, y_pred_continuous = predict_model(model, target_y_test,
                                         encoder_input_data_test, query_test)

1817/1817 [==============================] - 13s 7ms/step


In [140]:
type(y_pred_continuous)

numpy.ndarray

In [144]:
torch.save(torch.tensor(y_pred_binary), 'syn_cnn_pred_label.pt')
torch.save(torch.tensor(y_pred_continuous), 'syn_cnn_pred.pt')

In [9]:
model_lstm = keras.models.load_model(checkpoint_filepath_lstm)

In [10]:
model_lstm.summary()

Model: "functional_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, None, 512)]  0           []                               
                                                                                                  
 lstm (LSTM)                    [(None, 240),        722880      ['input_3[0][0]']                
                                 (None, 240),                                                     
                                 (None, 240)]                                                     
                                                                                                  
 tf_op_layer_concat (TensorFlow  (None, 480)         0           ['lstm[0][1]',                   
 OpLayer)                                                         'lstm[0][2]']        

In [146]:
y_pred_binary, y_pred_continuous = predict_model(model_lstm, target_y_test,
                                         encoder_input_data_test, query_test)

1817/1817 [==============================] - 108s 59ms/step


/opt/conda/envs/tf14/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [147]:
torch.save(torch.tensor(y_pred_binary), 'syn_lstm_pred_label.pt')
torch.save(torch.tensor(y_pred_continuous), 'syn_lstm_pred.pt')

In [149]:
lstm_y_pred_binary, lstm_y_pred_continuous = predict_model(model_lstm, target_val,
                                         encoder_input_val, query_input_val)

1272/1272 [==============================] - 75s 59ms/step


/opt/conda/envs/tf14/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [151]:
cnn_y_pred_binary, cnn_y_pred_continuous = predict_model(model, target_val,
                                         encoder_input_val, query_input_val)

1272/1272 [==============================] - 9s 7ms/step


In [150]:
torch.save(torch.tensor(lstm_y_pred_binary), 'val_syn_lstm_pred_label.pt')
torch.save(torch.tensor(lstm_y_pred_continuous), 'val_syn_lstm_pred.pt')

In [152]:
torch.save(torch.tensor(cnn_y_pred_binary), 'val_syn_cnn_pred_label.pt')
torch.save(torch.tensor(cnn_y_pred_continuous), 'val_syn_cnn_pred.pt')